App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug1>/", views.blog_details, name="blog_details"),
    path("liked_blog/<int:pk>/", views.liked_blog, name="liked_blog"),
    path("unliked_blog/<int:pk>/", views.unliked_blog, name="unliked_blog"),
    path("my_blogs/", views.MyBlogs.as_view(), name="my_blogs"),
    path("edit_blog/<int:pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path("signup/", views.sign_up ,name="signup"),
    path("login/", views.login_page ,name="login"),
    path("logout/", views.logout_page ,name="logout"),
    path("profile/", views.profile_page ,name="profile"),
    path("profileChange/", views.profile_change ,name="profileChange"),
    path("password/", views.password_change ,name="passwordChange"),
    path("profilePicChange/", views.profile_picture_change, name="profilePicChange"),
    path("profilePicUpdate/", views.profile_picture_update, name="profilePicUpdate"),
]

myBlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class userProfile(models.Model):
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics", verbose_name="Profile Picture")

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.urls import reverse
from App_Login.models import userProfile


class signUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    password2 = forms.CharField(label="Confirm Password ", required=True, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class userProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].help_text = (
            "Raw passwords are not stored, so there is no way to see this user's password, "
            "but you can change the password using <a href='{}'>this form</a>."
        ).format(reverse("App_Login:passwordChange"))


class userPasswordChangeForm(PasswordChangeForm):
    new_password2 = forms.CharField(label="Confirm Password ", required=True, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ("old_password", "new_password1", "new_password2")


class userProfilePictureChangeForm(forms.ModelForm):
    class Meta:
        model = userProfile
        fields = ("profile_pic",)

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from App_Login.forms import *
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def sign_up(request):
    form = signUpForm()
    registered = False
    if request.method == "POST":
        form = signUpForm(data=request.POST)
        if form.is_valid(): 
            form.save()
            registered = True
    
    context = {"form": form, "registered": registered}
    return render(request, "App_Login/signup.html", context=context)


def login_page(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("App_Blog:blog_list"))

    context = {
        "form": form
    }
    return render(request, "App_Login/login.html", context=context)


@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def profile_page(request):
    return render(request, "App_Login/profile.html")


@login_required
def profile_change(request):
    current_user = request.user
    changedProf = False
    form = userProfileChangeForm(instance = current_user)
    if request.method == "POST":
        form = userProfileChangeForm(request.POST, instance = current_user)
        if form.is_valid():
            form.save()
            changedProf = True
            form = userProfileChangeForm(instance = current_user)
    context = {
        "form": form,
        "changedProf": changedProf
    }
    return render(request, "App_Login/change_profile.html", context=context)

@login_required
def password_change(request):
    current_user = request.user
    changedPass = False
    form = userPasswordChangeForm(current_user)
    if request.method == "POST":
        form = userPasswordChangeForm(current_user, data = request.POST)
        if form.is_valid():
            form.save()
            changedPass = True
    context = {
        "form": form,
        "changedPass": changedPass
    }
    return render(request, "App_Login/change_password.html", context=context)

@login_required
def profile_picture_change(request):
    form = userProfilePictureChangeForm()

    if request.method == "POST":
        form = userProfilePictureChangeForm(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse("App_Login:profile"))

    context = {
        "form": form,
    }
    return render(request, "App_Login/change_profilePic.html", context=context)


@login_required
def profile_picture_update(request):
    form = userProfilePictureChangeForm(instance=request.user.user_profile)

    if request.method == "POST":
        form = userProfilePictureChangeForm(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("App_Login:profile"))

    context = {
        "form": form,
    }
    return render(request, "App_Login/change_profilePic.html", context=context)

templates/App_Login/change_password.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Update Profile
{% endblock %}

{% block body_block %}
    {% if changedPass %}
        <div class="alert alert-success">
            Password Changed Successfully
        </div>
    {% else %}
        <h2>Change Password</h2>
        <form method="POST">
            {% comment %} {{ form|crispy }} {% endcomment %}
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning btn-sm">Change Password</button>
        </form>
    {% endif %}
   
{% endblock %}

templates/App_Login/change_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Change Profile Info
{% endblock %}

{% block body_block %}

    <h2>Change Profile Info</h2>

    {% if changedProf %}
        <div class="alert alert-success">
            Profile Changed Successfully
        </div>
    {% endif %}
    
    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-warning btn-sm">Change Profile</button>
    </form>
    
   
{% endblock %}

templates/App_Login/change_profilePic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Change Profile Picture
{% endblock %}

{% block body_block %}

    <h2>Change Profile Picture</h2>

    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-warning btn-sm">Change Profile Picture</button>
    </form>
    
   
{% endblock %}

templates/App_Login/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Login
{% endblock %}

{% block body_block %}

    <h2>Account Login</h2>
    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Login</button>
    </form>
   
{% endblock %}

templates/App_Login/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Profile
{% endblock %}

{% block body_block %}

    <h2>Your Profile</h2>

    {% if user.user_profile %}
        <img src="/media/{{ user.user_profile.profile_pic }}" class="rounded border border-info border-3" width="100px">
        <br>
        <a href="{% url 'App_Login:profilePicUpdate' %}" class="btn btn-info btn-sm mt-2 mb-3">Update Profile Picture</a>
        <br>
    {% else %}
        <img src="/media/profile_pics/human.jpg" class="rounded border border-info border-3" width="100px">
        <br>
        <a href="{% url 'App_Login:profilePicChange' %}" class="btn btn-info btn-sm mt-2 mb-3">Change Profile Picture</a>
        <br>
    {% endif %}

    <table>
        <tr>
            <th>Username</th>
            <td class="pl-2">: {{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td class="pl-2">: {{ user.email }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td class="pl-2">: {{ user.first_name }} {{ user.last_name }}</td>
        </tr>
    </table>

    <br>
    <a class="btn btn-primary btn-sm" href="{% url 'App_Login:profileChange' %}">Change Profile Info</a>
   
    
   
{% endblock %}

templates/App_Login/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Create New Account
{% endblock %}

{% block body_block %}
    {% if registered %}
        <div class="alert alert-success">
            Account Created Successfully
            <a href="{% url 'App_Login:login' %}">Login Here</a>
        </div>
    {% else %}
        <h2>Create New Account</h2>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Create Account</button>
            <br><br>
            <p>Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
        </form>
    {% endif %}

{% endblock %}