App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug1>/", views.blog_details, name="blog_details"),
    path("liked_blog/<int:pk>/", views.liked_blog, name="liked_blog"),
    path("unliked_blog/<int:pk>/", views.unliked_blog, name="unliked_blog"),
    path("my_blogs/", views.MyBlogs.as_view(), name="my_blogs"),
    path("edit_blog/<int:pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path("signup/", views.sign_up ,name="signup"),
    path("login/", views.login_page ,name="login"),
    path("logout/", views.logout_page ,name="logout"),
    path("profile/", views.profile_page ,name="profile"),
    path("profileChange/", views.profile_change ,name="profileChange"),
    path("password/", views.password_change ,name="passwordChange"),
    path("profilePicChange/", views.profile_picture_change, name="profilePicChange"),
    path("profilePicUpdate/", views.profile_picture_update, name="profilePicUpdate"),
]

myBlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

	<title>
		{% block title_block %}
		Blogs
		{% endblock %}
	</title>

</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark pl-2 pr-2">
		<div class="container">
		  	<a class="navbar-brand" href="{% url 'index' %}"><img src="/media/blogLogo.png" width="80px"></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					{% if user.is_authenticated %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								@{{ user.username }}
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a></li>
								<li><a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a></li>
								<li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a></li>
								<hr>
								<li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
							</ul>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'App_Login:signup' %}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
						</li>
					{% endif %}
					
				</ul>
			</div>
		</div>
	  </nav>
	<div class="container pt-4" >
		{% block body_block %}

		{% endblock %}
	</div>


</body>
</html>