App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = "App_Blog"

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("write/", views.CreateBlog.as_view(), name="create_blog"),
    path("details/<slug:slug1>/", views.blog_details, name="blog_details"),
    path("liked_blog/<int:pk>/", views.liked_blog, name="liked_blog"),
    path("unliked_blog/<int:pk>/", views.unliked_blog, name="unliked_blog"),
    path("my_blogs/", views.MyBlogs.as_view(), name="my_blogs"),
    path("edit_blog/<int:pk>/", views.UpdateBlog.as_view(), name="edit_blog"),
]

myBlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "post_author")
    blog_title = models.CharField(max_length=255, verbose_name = "Put a Title")
    slug = models.SlugField(max_length=255, unique=True)
    blog_content = models.TextField(verbose_name = "What is on your mind?")
    blog_image = models.ImageField(upload_to="blog_images", verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ("-publish_date",)

    def __str__(self):
        return self.blog_title
    


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = "blog_comment")
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "user_comment")
    comment = models.TextField(verbose_name = "Write your comment here")
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-comment_date",)

    def __str__(self):
        return self.comment



class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = "blog_likes")
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "user_likes")

    def __str__(self):
        return self.user + "likes" + self.blog

App_Blog/forms.py
from django import forms
from App_Blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)
        widgets = {
          "comment": forms.Textarea(attrs={"rows":4, "class": "textAreaSize"}),
        }

App_Blog/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, View, ListView, TemplateView
from App_Blog.models import Blog, Comment, Likes
from App_Blog.forms import CommentForm


# Create your views here.
def blog_list(request):
    return render(request, 'App_Blog/blog_list.html', context={})


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = "App_Blog/create_blog.html"
    fields = ("blog_title","blog_content","blog_image")

    def form_valid(self, form):
        blog_obj1 = form.save(commit=False)
        blog_obj1.author = self.request.user
        title = blog_obj1.blog_title
        blog_obj1.slug = slugify(title) + "-" + str(uuid.uuid4())
        blog_obj1.save()

        return HttpResponseRedirect(reverse("index"))
    

class BlogList(ListView):
    model = Blog
    context_object_name = "blogs"
    template_name = "App_Blog/blog_list.html"
    # queryset = Blog.objects.order_by("-publish_date")


@login_required
def blog_details(request, slug1):
    blog = Blog.objects.get(slug=slug1)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse("App_Blog:blog_details", kwargs={"slug1": slug1}))
        
    context = {
        "blog": blog,
        "comment_form": comment_form,
        "liked": liked
    }
    return render(request, "App_Blog/blog_details.html", context=context)


@login_required
def liked_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user

    already_liked = Likes.objects.filter(blog=blog, user=user)

    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse("App_Blog:blog_details", kwargs={"slug1": blog.slug}))


@login_required
def unliked_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user

    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
   
    return HttpResponseRedirect(reverse("App_Blog:blog_details", kwargs={"slug1": blog.slug}))



class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = "App_Blog/my_blogs.html"

    
class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ("blog_title", "blog_content", "blog_image")
    template_name = "App_Blog/edit_blog.html"

    def get_success_url(self, **kwargs):
        return reverse_lazy("App_Blog:blog_details", kwargs={"slug1": self.object.slug})

templates/App_Blog/blog_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	{{ blog_title }}
{% endblock %}

{% block body_block %}
	<div class="row">
		<div class="col-sm-6">
			<h2>{{ blog.blog_title }}</h2>
			<h4>Posted By: @{{ blog.author }}</h4>
			<h6><i>Published On: {{ blog.publish_date }}</i></h6>
			<h6><i>Updated On: {{ blog.update_date }}</i></h6>
			<h6>
				<i class="fa-regular fa-thumbs-up" style="color: #3FB7B9;"></i>
				{{ blog.blog_likes.count }}
				<i class="fa-regular fa-message" style="color: #3FB7B9;"></i>
				{{ blog.blog_comment.count }}
			</h6>
		</div>
		<div class="col-sm-6">
			<img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%" height="300px">
		</div>
	</div>
	<br>
	<div class="row">
		<p class="text-justify">{{ blog.blog_content|linebreaksbr }}</p>
	</div>

	{% if liked %}
	<a href="{% url 'App_Blog:unliked_blog' pk=blog.pk %}" class="nav-link">
		<i class="fa-regular fa-thumbs-down fa-flip-horizontal fa-2x" style="color: #3FB7B9;"></i>
	</a>
	{% else %}
	<a href="{% url 'App_Blog:liked_blog' pk=blog.pk %}">
		<i class="fa-regular fa-thumbs-up fa-2x" style="color: #3FB7B9;"></i>
	</a>
	{% endif %}

	<h6>{{ blog.blog_likes.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
	
	<br>
	<hr>
	<div class="row">
		<h3>Comments</h3>
		<div class="col-sm-8">
			<form method="POST">
				{{ comment_form|crispy }}
				{% csrf_token %}
				<button type="submit" class="btn btn-primary btn-sm">Comment</button>
			</form>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-sm-8">
			{% for comment in blog.blog_comment.all %}
				<a href="#" class="nav-link text-primary">
					{% if comment.user.user_profile %}
						<img src="/media/{{ comment.user.user_profile.profile_pic }}" width="30px" height="30px" class="border rounded">
					{% else %}
						<img src="/media/profile_pics/human.jpg" width="30px" height="30px" class="border rounded">
					{% endif %}
					@{{ comment.user }}
					<span class="text-black">
						<i> • {{ comment.comment_date }} </i>
					</span>
				</a>
				<p class="text-justify">
					{{ comment.comment }}
					<br>
					<i class="fa-regular fa-thumbs-up" style="color: #B197FC;"></i>
					<i class="fa-regular fa-thumbs-down fa-flip-horizontal" style="color: #B197FC;"></i>
				</p>
			{% endfor %}
		</div>
	</div>
	<br>
	<br>
{% endblock %}

templates/App_Blog/blog_list.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title_block %}
	Home
{% endblock %}

{% block body_block %}

{% for blog in blogs %}
	<h3>{{ blog.blog_title }}</h3>
	<h6><i>{{ blog.publish_date }}</i></h6>
	<div class="row">
		<div class="col-sm-4">
			<img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%" height="300px">
		</div>
		<div class="col-sm-8">
			<p class="text-justify">{{ blog.blog_content|range_filter|linebreaksbr }}<a href="{% url 'App_Blog:blog_details' slug1=blog.slug %}">Read More</a></p>
			<h6><strong>Posted By: @</strong><a href="#">{{ blog.author }}</a></h6>
			<h6>
				<i class="fa-regular fa-thumbs-up" style="color: #3FB7B9;"></i>
				{{ blog.blog_likes.count }}
				<i class="fa-regular fa-message" style="color: #3FB7B9;"></i>
				{{ blog.blog_comment.count }}
			</h6>
		</div>
	</div>
	<br><hr>
{% endfor %}

{% endblock %}

templates/App_Blog/create_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	Create New Blog
{% endblock %}

{% block body_block %}

	<h2>Write Your Blog:</h2>
	<form method="POST" enctype="multipart/form-data">
		{{ form|crispy }}
		{% csrf_token %}
		<button type="submit" class="btn btn-success btn-sm">Publish</button>
	</form>

{% endblock %}

templates/App_Blog/edit_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %}
	{{ blog.blog_title }}
{% endblock %}

{% block body_block %}
{% if blog.author == user %}
	<form method="POST" enctype="multipart/form-data">
		{{ form|crispy }}
		{% csrf_token %}
		<button type="submit" class="btn btn-success btn-sm">Update</button>
	</form>
{% else %}
<div class="alert alert-secondary text-center">
	<h2>404</h2>
	<h4>You are not allowed to view this page.</h4>
</div>
{% endif %}
{% endblock %}

templates/App_Blog/my_blogs.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block title_block %}
	My Blogs
{% endblock %}

{% block body_block %}
	{% if user.post_author %}
		{% for blog in user.post_author.all %}
		<h3>{{ blog.blog_title }}</h3>
		<h6><i>{{ blog.publish_date }}</i></h6>
		<div class="row">
			<div class="col-sm-4">
				<img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%" height="300px">
			</div>
			<div class="col-sm-8">
				<p class="text-justify">{{ blog.blog_content|range_filter|linebreaksbr }}<a href="{% url 'App_Blog:blog_details' slug1=blog.slug %}">Read More</a></p>
				<h6>
					<i class="fa-regular fa-thumbs-up" style="color: #3FB7B9;"></i>
					{{ blog.blog_likes.count }}
					<i class="fa-regular fa-message" style="color: #3FB7B9;"></i>
					{{ blog.blog_comment.count }}
				</h6>
				<br>
				<button class="btn btn-sm btn-info"><a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}" class="nav-link">Edit Blog</a></button>
			</div>
		</div>
		<br><hr>
		{% endfor %}
	{% else %}
		<h4 class="alert alert-secondary">You haven't written any blog yet.</h4>
		<button class="btn btn-primary"><a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog</a></button>
	{% endif %}
{% endblock %}